
const GET_INDONESIA = "GET_INDONESIA"
const SET_LOADING  = "SET_LOADING"
const GET_GLOBALS = "GET_GLOBALS"
const GET_DAILY = "GET_DAILY"
const GET_COUNTRY =  "GET_COUNTRY"
const GET_CASES_COUNTRY = "GET_CASES_COUNTRY"
export {GET_INDONESIA,SET_LOADING,GET_GLOBALS, GET_DAILY,GET_COUNTRY,GET_CASES_COUNTRY}